### ISSUE TITLE
EOFError: read end of file

### ISSUE THREAD

**Issue by merckxiaan** [JuliaIO/DICOM.jl#33] opened 2019-07-17 19:56 UTC
I got some DICOM images from a Kaggle competition and tried parsing one of them in Julia but got this error:
```julia
EOFError: read end of file

Stacktrace:
 [1] unsafe_read at .\iostream.jl:413 [inlined]
 [2] unsafe_read at .\io.jl:585 [inlined]
 [3] macro expansion at .\gcutils.jl:87 [inlined]
 [4] read! at .\io.jl:597 [inlined]
 [5] element(::IOStream, ::Bool, ::Dict{Tuple{UInt16,UInt16},Any}, ::Dict{Tuple{UInt16,UInt16},String}) at C:\Users\jules\.julia\packages\DICOM\Tu30N\src\DICOM.jl:377
 [6] #dcm_parse#17(::Bool, ::UInt16, ::Dict{Tuple{UInt16,UInt16},String}, ::Function, ::String, ::Bool) at C:\Users\jules\.julia\packages\DICOM\Tu30N\src\DICOM.jl:524
 [7] dcm_parse at C:\Users\jules\.julia\packages\DICOM\Tu30N\src\DICOM.jl:501 [inlined] (repeats 2 times)
 [8] top-level scope at In[3]:1
```
Am I doing something wrong or is this reproducible?
[sample images.zip](https://github.com/JuliaIO/DICOM.jl/files/3403599/sample.images.zip)

Versioninfo:
```
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by notZaki** [comment] 2019-07-18 19:23
I was able to reproduce the error.

There's two reasons why the files couldn't be parsed: (i) there was a bug in the package and (ii) the images are JPEG-compressed.

The pending pull request should resolve the bug. 
In the mean time, the local package can be updated by
```
julia> ]dev DICOM
```
and then navigating to the dev directory and pulling the `specifyLength_AS` branch from [my fork](https://github.com/notZaki/DICOM.jl/tree/specifyLength_AS), e.g.
```
git pull https://github.com/notZaki/DICOM.jl.git specifyLength_AS
```

With the above fix, those DICOM files can be parsed, but the pixel data will be incorrect because this package does not support JPEG-compressed images. These can be decompressed by using an external tool. 
I used GDCM [(download)](https://github.com/malaterre/GDCM/releases). Once it is installed and in the system path, the DICOM files can be decompressed by running `gdcmconv --raw compressed.dcm uncompressed.dcm`.

---

For reference, I'm including the code that I used to test it out along with a screengrab of the plotted image. The pixel data will likely have to be flipped/transposed to get the right orientation.
 
```Julia
# The folder containing the DICOM files
datafolder = joinpath(pwd(), "sample.images")

# Get the filenames of only the dicom files
datafiles = readdir(datafolder)
isDICOM = [splitext(file)[2]==".dcm" for file in datafiles]
dicomfiles = datafiles[isDICOM]

# Use GDCM to decompress the dicom files
outfolder = joinpath(pwd(), "samples.images.decompressed")
mkdir(outfolder) # [!] assumes outfolder doesn't exist
for file in dicomfiles
    inputfile = joinpath(datafolder, file)
    outputfile = joinpath(outfolder, file)
    run(`gdcmconv --raw $inputfile $outputfile`)
end

# Pick any of the decompressed files and parse it
using DICOM
chosenfile = joinpath(outfolder, dicomfiles[1])
dicomdata = dcm_parse(chosenfile)

# Display the pixel data from the parsed file
using Plots
gr()
pixeldata =  dicomdata[tag"Pixel Data"]
heatmap(pixeldata, aspect_ratio=1, color=:grays)
```
![image](https://user-images.githubusercontent.com/9019681/61485485-496f3680-a96f-11e9-99d4-dfae57d49012.png)

**Comment by merckxiaan** [comment] 2019-07-18 20:25
WOW, thanks a lot!
This is really great!!!

**Closed** 2019-11-16 21:49 UTC
